// The five RUSLE factor maps were imported 
var R = ee.Image("projects/zippy-hold-481312-t0/assets/R_factor");
var K = ee.Image("projects/zippy-hold-481312-t0/assets/K_factor");
var LS = ee.Image("projects/zippy-hold-481312-t0/assets/LS_factor");
var C = ee.Image("projects/zippy-hold-481312-t0/assets/C_factor");
var P = ee.Image("projects/zippy-hold-481312-t0/assets/P_factor");

// Observed erosion points were imported from a shapefile uploaded to GEE
var erosionPoints = ee.FeatureCollection("projects/zippy-hold-481312-t0/assets/Erosion_Output");

// The input image was constructed by stacking the five RUSLE factors as separate bands
var inputImage = R.rename('R')
                  .addBands(K.rename('K'))
                  .addBands(LS.rename('LS'))
                  .addBands(C.rename('C'))
                  .addBands(P.rename('P'));

// A training dataset was generated by sampling the RUSLE factors at the erosion point locations
var trainingData = inputImage.sampleRegions({
  collection: erosionPoints,
  properties: ['Erosion'],  
  scale: 30,                
  geometries: true
});

// A Random Forest model was configured for regression with 500 trees
var regressor = ee.Classifier.smileRandomForest({
  numberOfTrees: 500
}).setOutputMode('REGRESSION');

// The model was trained using the extracted training dataset
var trained = regressor.train({
  features: trainingData,
  classProperty: 'Erosion',
  inputProperties: ['R', 'K', 'LS', 'C', 'P']
});

// The trained model was applied to the full set of predictor variables to generate a continuous erosion map
var predictedErosion = inputImage.classify(trained);

// The resulting erosion map was visualized as a continuous surface
Map.centerObject(erosionPoints, 8);
Map.addLayer(predictedErosion, {
  min: 0,             
  max: 50,           
  palette: ['green', 'yellow', 'orange', 'red']
}, 'Predicted Erosion (Continuous)');

// The predicted erosion map was exported to Google Drive for further analysis
Export.image.toDrive({
  image: predictedErosion,
  description: 'Predicted_Erosion_RF',
  scale: 30,
  region: inputImage.geometry(),  
  maxPixels: 1e13
});
